model:
  base_momentum: 0.99
  backbone:
    type: "resnet50"
    pretrained: false
  projection:   # src: A.2 of detcon paper
    type: "MLP" 
    input_dim: 2048
    hidden_dim: 4096
    output_dim: 256
  predictor:
    type: "MLP"
    input_dim: 256
    hidden_dim: 4096
    output_dim: 256

amp:
  sync_bn: False
  opt_level: "O0"

data: 
  image_dir: "/media/mattyb/UBUNTU 22_0/our_data/datasets/imagenet_strawberries/" #TODO: Change to match Japan Cluster
  subset: ""
  mask_type: "fh"
  resize_size: 224 # src: 3.1
  data_workers: 1
  train_batch_size: 8 # src: A.3 (Global should be 4096 = batch_size x num_gpu)
  val_batch_size: 8 #  Should not matter
  dual_views: true
  num_examples: 860

optimizer:
  type: lars
  base_lr: 0.3
  lr_type: "cosine"
  momentum: 0.9 # src: Deepmind code config
  weight_decay: 1.0e-6
  total_epochs: 20 #! change this to be larger
  warmup_epochs: 1 # src: Deepmind code; should be 1/100 of total epoches
  exclude_bias_and_bn: true

loss: #src: 3.1
  temperature: 0.1
  mask_rois: 16
  pool_size: 7 #7, 14, 28, 56
  
checkpoint:
  time_stamp:
  resume_path:
  save_epoch: 30
  ckpt_path: "ckpt/detconb_imagenet/{}/{}_{}_{}.pth.tar"

log:
  log_step: 10
  log_dir: "logs"
  log_all: True
  enable_wandb: True

stage: "train"
distributed: false
seed: 0
